const
  FAR_LOOK* = 8
  VERB_WALKTO = 1
  VERB_LOOKAT* = 2
  VERB_TALKTO* = 3
  VERB_PICKUP = 4
  VERB_OPEN = 5
  VERB_CLOSE = 6
  VERB_PUSH = 7
  VERB_PULL = 8
  VERB_GIVE = 9
  VERB_USE = 10
  VERB_DIALOG = 13
type
  VerbId* = int
